server:
  port: 8080

logging:
  config: 'classpath:logback.xml'
  level:
    com.thepointmoscow.frws: DEBUG

task.delay: 30

fiscal:
  server:
    type: 'mock'
    host: '127.0.0.1'
    port: 4545

backend:
  server:
    url: 'https://app.ecomkassa.ru'
    username: 'test@test.test'
    password: 'test'
    ccmID: '519471b6-5d27-4844-8fa0-032698926b18'