version: '2'
services:
  mongo:
    image: "mongo:3.5.10"
    ports:
     - "27017:27017"
    volumes:
     - /var/docker/data/mongo/:/data/db
  backend:
    image: "unlocker/mobilepos-backend:latest"
    links:
     - mongo
    ports:
     - "9000:9000"
     - "9443:9443"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test
     - PLAY_CRYPTO_SECRET=abcdefghijk
