version: '2'
services:
  mongo:
    image: "mongo:3.5.10"
    ports:
     - "27017:27017"
    volumes:
     - /var/docker/data/mongo/:/data/db
    command: ["mongod", "--bind_ip_all", "--auth"]
  backend:
    image: "unlocker/mobilepos-backend:latest"
    links:
     - mongo
    ports:
     - "9000:9000"
     - "9443:9443"
    environment:
     - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PWD}@mongo:27017/test
     - PLAY_CRYPTO_SECRET=abcdefghijk
#  items:
#      image: "unlocker/mobilepos-backend:ITEMS-latest"
#      ports:
#       - "8081:8080"
  migrator:
    image: "unlocker/mobilepos-backend:MMM-latest"
    links:
     - mongo
    environment:
     - SPRING_DATA_MONGODB_HOST=mongo
     - SPRING_DATA_MONGODB_DATABASE=test
     - SPRING_DATA_MONGODB_PORT=27017
     - SPRING_DATA_MONGODB_USERNAME=$MONGO_USER
     - SPRING_DATA_MONGODB_PASSWORD=$MONGO_PWD